import fs from 'fs';
import path from 'path';

export interface Post {
  id: number;
  slug: string;
  title: string;
  content: string;
  date: string;
  lang?: string;
}

const dataDirectory = path.join(process.cwd(), 'data');

// ---------------------------------------------------------------------------
// English (source) posts — data/posts.json
// ---------------------------------------------------------------------------
export function getAllPosts(): Post[] {
  const filePath = path.join(dataDirectory, 'posts.json');
  const jsonData = fs.readFileSync(filePath, 'utf-8');
  const posts: Post[] = JSON.parse(jsonData);
  return posts.sort((a, b) => (a.date < b.date ? 1 : -1));
}

export function getPostBySlug(slug: string): Post | undefined {
  const posts = getAllPosts();
  return posts.find((post) => post.slug === slug);
}

// ---------------------------------------------------------------------------
// Hindi (translated) posts — data/posts-translated.json
// Generated by scripts/translate-posts.js, which runs as an npm "prebuild"
// hook. Powers the /hi/[slug] route.
// ---------------------------------------------------------------------------
export function getAllPostsHi(): Post[] {
  const filePath = path.join(dataDirectory, 'posts-translated.json');

  if (!fs.existsSync(filePath)) {
    console.warn(
      `[lib/posts] ${filePath} not found. Run "npm run translate" to generate Hindi posts.`
    );
    return [];
  }

  const jsonData = fs.readFileSync(filePath, 'utf-8');
  const posts: Post[] = JSON.parse(jsonData);
  return posts.sort((a, b) => (a.date < b.date ? 1 : -1));
}

export function getPostBySlugHi(slug: string): Post | undefined {
  const posts = getAllPostsHi();
  return posts.find((post) => post.slug === slug);
}